### ISSUE TITLE
Work checklist for Omar

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/coordination#1]
- [ ] Setup bedrock-dev
- [ ] Setup authorization.dev
- [ ] Setup issuer.truecred.dev
- [ ] Setup idp.truecred.dev
- [ ] Setup consumer.truecred.dev
- [ ] Understand the new flow on authorization.dev and explain it to Dave or Manu
- [ ] Create work schedule and commit to times
- [ ] Create 20 year plan for both professional life and personal life
- [ ] Life plan review with Manu
- [ ] Performance review with Manu
- [ ] Create measurable goals for next 3 months based on life plan and performance review (setup for next performance review.

**Comment by dlongley** [comment]
Closing as old.
